# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/danielmccray/GroupProjectC++2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/danielmccray/GroupProjectC++2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danielmccray/GroupProjectC++2/CMakeFiles /Users/danielmccray/GroupProjectC++2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danielmccray/GroupProjectC++2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ExecuteMe

# Build rule for target.
ExecuteMe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExecuteMe
.PHONY : ExecuteMe

# fast build rule for target.
ExecuteMe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/build
.PHONY : ExecuteMe/fast

src/Course.o: src/Course.cpp.o
.PHONY : src/Course.o

# target to build an object file
src/Course.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/Course.cpp.o
.PHONY : src/Course.cpp.o

src/Course.i: src/Course.cpp.i
.PHONY : src/Course.i

# target to preprocess a source file
src/Course.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/Course.cpp.i
.PHONY : src/Course.cpp.i

src/Course.s: src/Course.cpp.s
.PHONY : src/Course.s

# target to generate assembly for a file
src/Course.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/Course.cpp.s
.PHONY : src/Course.cpp.s

src/course_list_insert_in_order/CourseListInsertInOrder.o: src/course_list_insert_in_order/CourseListInsertInOrder.cpp.o
.PHONY : src/course_list_insert_in_order/CourseListInsertInOrder.o

# target to build an object file
src/course_list_insert_in_order/CourseListInsertInOrder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/course_list_insert_in_order/CourseListInsertInOrder.cpp.o
.PHONY : src/course_list_insert_in_order/CourseListInsertInOrder.cpp.o

src/course_list_insert_in_order/CourseListInsertInOrder.i: src/course_list_insert_in_order/CourseListInsertInOrder.cpp.i
.PHONY : src/course_list_insert_in_order/CourseListInsertInOrder.i

# target to preprocess a source file
src/course_list_insert_in_order/CourseListInsertInOrder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/course_list_insert_in_order/CourseListInsertInOrder.cpp.i
.PHONY : src/course_list_insert_in_order/CourseListInsertInOrder.cpp.i

src/course_list_insert_in_order/CourseListInsertInOrder.s: src/course_list_insert_in_order/CourseListInsertInOrder.cpp.s
.PHONY : src/course_list_insert_in_order/CourseListInsertInOrder.s

# target to generate assembly for a file
src/course_list_insert_in_order/CourseListInsertInOrder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/course_list_insert_in_order/CourseListInsertInOrder.cpp.s
.PHONY : src/course_list_insert_in_order/CourseListInsertInOrder.cpp.s

src/implementation/CourseList.o: src/implementation/CourseList.cpp.o
.PHONY : src/implementation/CourseList.o

# target to build an object file
src/implementation/CourseList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/implementation/CourseList.cpp.o
.PHONY : src/implementation/CourseList.cpp.o

src/implementation/CourseList.i: src/implementation/CourseList.cpp.i
.PHONY : src/implementation/CourseList.i

# target to preprocess a source file
src/implementation/CourseList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/implementation/CourseList.cpp.i
.PHONY : src/implementation/CourseList.cpp.i

src/implementation/CourseList.s: src/implementation/CourseList.cpp.s
.PHONY : src/implementation/CourseList.s

# target to generate assembly for a file
src/implementation/CourseList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/implementation/CourseList.cpp.s
.PHONY : src/implementation/CourseList.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/test_copy_constructor/TestCopyConstructor.o: src/test_copy_constructor/TestCopyConstructor.cpp.o
.PHONY : src/test_copy_constructor/TestCopyConstructor.o

# target to build an object file
src/test_copy_constructor/TestCopyConstructor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/test_copy_constructor/TestCopyConstructor.cpp.o
.PHONY : src/test_copy_constructor/TestCopyConstructor.cpp.o

src/test_copy_constructor/TestCopyConstructor.i: src/test_copy_constructor/TestCopyConstructor.cpp.i
.PHONY : src/test_copy_constructor/TestCopyConstructor.i

# target to preprocess a source file
src/test_copy_constructor/TestCopyConstructor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/test_copy_constructor/TestCopyConstructor.cpp.i
.PHONY : src/test_copy_constructor/TestCopyConstructor.cpp.i

src/test_copy_constructor/TestCopyConstructor.s: src/test_copy_constructor/TestCopyConstructor.cpp.s
.PHONY : src/test_copy_constructor/TestCopyConstructor.s

# target to generate assembly for a file
src/test_copy_constructor/TestCopyConstructor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/test_copy_constructor/TestCopyConstructor.cpp.s
.PHONY : src/test_copy_constructor/TestCopyConstructor.cpp.s

src/test_function/TestFunctions.o: src/test_function/TestFunctions.cpp.o
.PHONY : src/test_function/TestFunctions.o

# target to build an object file
src/test_function/TestFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/test_function/TestFunctions.cpp.o
.PHONY : src/test_function/TestFunctions.cpp.o

src/test_function/TestFunctions.i: src/test_function/TestFunctions.cpp.i
.PHONY : src/test_function/TestFunctions.i

# target to preprocess a source file
src/test_function/TestFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/test_function/TestFunctions.cpp.i
.PHONY : src/test_function/TestFunctions.cpp.i

src/test_function/TestFunctions.s: src/test_function/TestFunctions.cpp.s
.PHONY : src/test_function/TestFunctions.s

# target to generate assembly for a file
src/test_function/TestFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/test_function/TestFunctions.cpp.s
.PHONY : src/test_function/TestFunctions.cpp.s

src/the_big_three/CourseListBigThree.o: src/the_big_three/CourseListBigThree.cpp.o
.PHONY : src/the_big_three/CourseListBigThree.o

# target to build an object file
src/the_big_three/CourseListBigThree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/the_big_three/CourseListBigThree.cpp.o
.PHONY : src/the_big_three/CourseListBigThree.cpp.o

src/the_big_three/CourseListBigThree.i: src/the_big_three/CourseListBigThree.cpp.i
.PHONY : src/the_big_three/CourseListBigThree.i

# target to preprocess a source file
src/the_big_three/CourseListBigThree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/the_big_three/CourseListBigThree.cpp.i
.PHONY : src/the_big_three/CourseListBigThree.cpp.i

src/the_big_three/CourseListBigThree.s: src/the_big_three/CourseListBigThree.cpp.s
.PHONY : src/the_big_three/CourseListBigThree.s

# target to generate assembly for a file
src/the_big_three/CourseListBigThree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExecuteMe.dir/build.make CMakeFiles/ExecuteMe.dir/src/the_big_three/CourseListBigThree.cpp.s
.PHONY : src/the_big_three/CourseListBigThree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ExecuteMe"
	@echo "... src/Course.o"
	@echo "... src/Course.i"
	@echo "... src/Course.s"
	@echo "... src/course_list_insert_in_order/CourseListInsertInOrder.o"
	@echo "... src/course_list_insert_in_order/CourseListInsertInOrder.i"
	@echo "... src/course_list_insert_in_order/CourseListInsertInOrder.s"
	@echo "... src/implementation/CourseList.o"
	@echo "... src/implementation/CourseList.i"
	@echo "... src/implementation/CourseList.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/test_copy_constructor/TestCopyConstructor.o"
	@echo "... src/test_copy_constructor/TestCopyConstructor.i"
	@echo "... src/test_copy_constructor/TestCopyConstructor.s"
	@echo "... src/test_function/TestFunctions.o"
	@echo "... src/test_function/TestFunctions.i"
	@echo "... src/test_function/TestFunctions.s"
	@echo "... src/the_big_three/CourseListBigThree.o"
	@echo "... src/the_big_three/CourseListBigThree.i"
	@echo "... src/the_big_three/CourseListBigThree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

